### PR TITLE
Restrict the ajax downloads search to titles only

### LINKED ISSUE #9508: Look into updating edd_ajax_download_search to search titles only
### Explain your enhancement (please be detailed)
A customer is reporting that the `edd_ajax_download_search` function is returning unexpected, and too many, results. I think the primary reason for this is that it is using the standard search parameter for the core WP function `get_posts` and that kind of query searches not only the title (which is really what would be most useful and appropriate for the product dropdown), but also the excerpt and content. Here's a stripped down example of the query:

```
SELECT wp_posts.ID
FROM wp_posts
WHERE 1=1
AND (((wp_posts.post_title LIKE '%licensed%')
OR (wp_posts.post_excerpt LIKE '%licensed%')
OR (wp_posts.post_content LIKE '%licensed%')))
AND wp_posts.post_type = 'download'
AND ((wp_posts.post_status = 'publish'))
ORDER BY wp_posts.post_date DESC
LIMIT 0, 5
```

### Justification or use case
I think if the product dropdown searched only the titles, it would give more expected results for users, who are probably really just searching by title in this context, and it should be faster.

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #9508

Proposed Changes:
1. Adds a filter on the `WHERE` clause for the ajax downloads search. This restricts the search to run on the download titles only, instead of including the content and excerpt.

### CODE REVIEW

File: includes/ajax-functions.php [hunk 1]
```diff
@@ -724,9 +727,28 @@ function edd_ajax_download_search() {
...
+ * Filters the WHERE SQL query for the edd_download_search.
+ * This searches the download titles only, not the excerpt/content.
+ *
+ * @since 3.1.0.2
+ * @param string $where
+ * @param WP_Query $wp_query
+ * @return string
+ */
+function edd_ajax_filter_download_where( $where, $wp_query ) {
+	$search = $wp_query->get( 'edd_search' );
```
Comment (cklosowski) [inline includes/ajax-functions.php:743]: We should be use `esc_like` to do proper sanitization of the search query before using it.
https://developer.wordpress.org/reference/classes/wpdb/esc_like/

**Review by cklosowski — CHANGES_REQUESTED** [review]

**Comment by cklosowski** [comment]
This I believe is unrelated as I can produce it on `release/3.1.0.2`, but the `(All Price Options)` is being added to all items after searching, pushed up a change to address that while we're in here making changes.

Initial Page load and opening the chosen box, A Music Album is showing the All option as well as every price option.
image

Once searching I end up with all the options still but they have '(All Options)' added to them:
image

**Comment by robincornett** [comment]
Just noting that I see the issue you've flagged @cklosowski and agree with your fix.

**Review by cklosowski — APPROVED** [review]
