### PR TITLE
Do not send purchase email when creating a refund

### LINKED ISSUE #9025: 3.0 - New purchase email is sent after a refund
### Expected behavior
When I issue a refund, I do not expect to get a "new purchase" email. (The admin one.)

### Actual behavior
I'm pretty sure I received one.

### Steps to reproduce the behavior
1) Start with a complete order.
2) Refund that order.
3) See that you (the admin) received a new purchase notification email.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #9025 

Proposed Changes:
1. Updates `edd_trigger_purchase_receipt` to check for the order type and returns early if it's a `refund`.

### CODE REVIEW

**Review by ashleyfae — CHANGES_REQUESTED** [review]

File: includes/emails/actions.php [hunk 1]
```diff
@@ -28,6 +28,12 @@ function edd_trigger_purchase_receipt( $payment_id = 0, $payment = null, $custom
 	if ( isset( $_POST['edd-action'] ) && 'edit_payment' == $_POST['edd-action'] ) {
 		return;
 	}
+	if ( null === $payment ) {
+		$payment = new EDD_Payment( $payment_id );
+	}
+	if ( 'refund' === $payment->order->type ) {
```
Comment (ashleyfae) [inline includes/emails/actions.php:34]:
```suggestion
	if ( $payment->order instanceof \EDD\Orders\Order && 'refund' === $payment->order->type ) {
```

In the unlikely event that `$payment->order` ended up `false`.

**Review by ashleyfae — APPROVED** [review]
