### PR TITLE
Fix and improve discount validation logic

### LINKED ISSUE #9110: 3.0 - edd_validate_discount product requirements logic is incorrect
### Expected behavior
When validating a discount, the `foreach` loop logic is incorrect for product requirements. See the following code:

```
	if ( ! empty( $product_requirements ) ) {
		foreach ( $product_requirements as $download_id ) {
			if ( empty( $download_id ) ) {
				continue;
			}

			$download_id  = absint( $download_id );
			$has_download = in_array( $download_id, $download_ids, true );

			switch ( $discount->get_product_condition() ) {
				case 'all':
					$is_valid = false !== $has_download;
					break;
				default:
					$is_valid = $has_download;
			}
		}
	} else {
		$is_valid = true;
	}
```

When the `default` case is hit, once the final array element is validated it could end up being false instead of true (like the other items), breaking the logic for the check.

Additionally because we are only dealing with IDs (and not variable priced products), using an `array_intersect` is a about 10 times faster than a foreach. This could also apply to the exclusions also, which would increase performance. 

### Actual behavior
If the last item product requirement is NOT in the cart, this will result in a false which is wrong. As it should be true for ANY of the items.

I will submit a PR to fix this issue and improve the performance of this function.

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #9110

This is a revision/extension of the work @davidsherlock did in #9111. The product requirements/exclusions logic are all his; I just did a bit of logic reorganization for improved readability.

Proposed Changes:
1. Updates the doc block for `edd_validate_discount` to better explain what the function does and does not cover.
2. Moves/updates the initial `$is_valid` variable assignment as it was always being overwritten.
3. Updates the discount class' `is_product_requirements_met` method to match this logic and use the array_intersect approach so that the class method is consistent with this new function.
4. Adds unit tests to cover `edd_validate_discount`.

Note that if you copy the unit tests to the release/3.0 branch, they do fail, which I believe is an additional confirmation of David's findings.

David, it looks like I cannot officially add you to this as a reviewer, but I would greatly appreciate your review. Thank you for the PR!

### CODE REVIEW

**Comment by davidsherlock** [comment]
Thanks, @robincornett! Looks good to me. Code also looks more beautiful now.

As a side note, on a related note to discounts there is a pretty serious issue with flat rate discounts I posted a while back. I need to find 15 minutes or so to write up a proper fix for this, but you can see the issue I opened here: #8757 

Because I am building a bunch of new EDD 3.0 extensions, I am uncovering some small issues like this. Though the discount one is pretty serious as the flat rate amount is essentially added multiple times.

File: tests/discounts/tests-discounts.php [hunk 1]
```diff
@@ -393,6 +393,57 @@ public function test_discount_is_product_requirements_met() {
...
+		$args     = array(
+			'product_reqs'      => $products,
+			'product_condition' => 'any',
+			'max_uses'          => 10000,
+		);
+
+		edd_update_discount( self::$discount_id, $args );
+		$this->assertTrue( edd_validate_discount( self::$discount_id, $products ) );
+		$this->assertTrue( edd_validate_discount( self::$discount_id, array( self::$download->ID ) ) );
+		$this->assertTrue( edd_validate_discount( self::$discount_id, array( 100 ) ) );
```
Comment (robincornett) [inline tests/discounts/tests-discounts.php:410]: I'm feeling like the tests should also cover sending in a product which is _not_ part of the product requirements. But before I get too excited about adding in more assertions, I want to check with you, @cklosowski about it because on a recent PR you said we should limit the number of assertions per test. We do, however, have quite a few tests which have multiple (and even many) assertions, so my question is:
1. If the assertions cover an identical discount setup (like the discount should not change as in this method), is it okay to have multiple assertions?
2. I updated the discount object in this method and then again in both of the following methods, but I'm wondering if the modified discount is what's used in each. I wrote the update args assuming that was the case both ways.
3. It seems like the `test_discount_is_product_requirements_met` method should also test for an expected false return but it doesn't.

Anyway I would hypothetically like to add assertions for a hypothetical product which is not listed in the requirements, eg: 
```php
		$products[] = 3467;
		$this->assertFalse( edd_validate_discount( self::$discount_id, array( 3467 ) ) );
		$this->assertTrue( edd_validate_discount( self::$discount_id, $products ) );
```

**Review by cklosowski — APPROVED** [review]
