### PR TITLE
Destroy order and customer when deleting a customer #9420

### LINKED ISSUE #9420: Bug: Deleting a customer & their orders turns into refunds
### Expected behavior

I expect that deleting a customer and all their records removes the data completely, and their numbers are removed from reporting.

### Actual behavior

Deleted orders are turned into refunds, they only appear in new 'refunds' tab. The deleted orders are counted as refunds in the reports. This is big issue when cleaning up test orders etc. 

One a side note: what's the point of the new Refunds tab? I'm confused to why there are refunds in two locations.

### Steps to reproduce the behavior

1) Go to a customer page and delete them ( ✅ Are you sure you want to delete this customer? ✅ Delete all associated payments and records?)
2) Customer orders are deleted, they don't appear in the standard orders list.
3) Somehow duplicate versions of the orders appear in the "Refunds" tab. These fake 'refunds' also show up in reports?

Screenshot for reference below

### Information (if a specific version is affected):
PHP Version: 7.4

EDD Version (or branch): Version 3.0.4

WordPress Version: 6.0.2

Screen Shot 2022-09-07 at 12 32 57
 relevant information:

### PR DESCRIPTION
**Pull request by cklosowski**
Fixes #9420 

Proposed Changes:
1. Swaps the delete customer action to use `destroy` functions instead.

### CODE REVIEW

File: includes/admin/customers/customer-actions.php [hunk 1]
```diff
@@ -447,15 +447,15 @@ function edd_customer_delete( $args = array() ) {
...
+		$success        = edd_destroy_customer( $customer->id );
 
 		if ( $success ) {
 
 			if ( $remove_data ) {
 
 				// Remove all payments, logs, etc
 				foreach ( $payments_array as $payment_id ) {
-					edd_delete_purchase( $payment_id, false, true );
+					edd_destroy_order( $payment_id, false, true );
```
Comment (robincornett) [inline includes/admin/customers/customer-actions.php:458]:
```suggestion
					edd_destroy_order( $payment_id );
```
This function only takes one parameter.

**Review by robincornett — APPROVED** [review]
